version: '2.4'
services:
  db:
    image: mysql
    container_name: marmoraria
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - marmoraria_data:/var/lib/mysql/

volumes:
  marmoraria_data: