version: '2.4'

services:
  db_marmoraria:
    image: postgres
    container_name: marmoraria_db
    environment:
    ports:
      - "5433:5432"
    volumes:
      - marmoraria_data:/var/lib/postgresql/data

volumes:
  marmoraria_data:
